// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	code "github.com/stamford-syntax-club/style-war/backend/app/code"
	mock "github.com/stretchr/testify/mock"
)

// CodeRepo is an autogenerated mock type for the CodeRepo type
type CodeRepo struct {
	mock.Mock
}

// GetCode provides a mock function with given fields:
func (_m *CodeRepo) GetCode() *code.Code {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetCode")
	}

	var r0 *code.Code
	if rf, ok := ret.Get(0).(func() *code.Code); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*code.Code)
		}
	}

	return r0
}

// NewCodeRepo creates a new instance of CodeRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCodeRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *CodeRepo {
	mock := &CodeRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
