apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: syntax-ingress
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: fe-service
                port:
                  number: 3000
    #
    # - host: "stylewars-be.*"
    #   http:
    #     paths:
    #       - pathType: Prefix
    #         path: "/foo"
    #         backend:
    #           service:
    #             name: service2
    #             port:
    #               number: 80
