apiVersion: apps/v1
kind: Deployment
metadata:
  name: be-deployment
  labels:
    app.kubernetes.io/name: be
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: be
  template:
    metadata:
      labels:
        app.kubernetes.io/name: be
    spec:
      containers:
        - name: be
          image: chinathaip/stylewars-be:12-aug
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: be-svc-port
          envFrom:
            - secretRef:
                name: be-secret

---
apiVersion: v1
kind: Service
metadata:
  name: be-service
spec:
  selector:
    app.kubernetes.io/name: be
  ports:
    - name: be-port
      protocol: TCP
      port: 8080
      targetPort: be-svc-port
